# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_auto_20190310_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfollower', to=settings.AUTH_USER_MODEL)),
                ('user_following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfollowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
