# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0004_auto_20190311_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagelikes', to='instagram.Image')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
